#  general description of this module
#  $Id: Makefile,v 1.1.1.1 2008-05-28 07:35:00 kent Exp $
#  @author $Author: kent $
#  @date $Date: 2008-05-28 07:35:00 $
#  @version 1.0
#  @note Editor: Vim 6.1, Gcc 4.0.2, tab=4
#  @note Platform: Linux


TDR_CFILE=$(wildcard *.cpp)
TDR_OBJ=$(TDR_CFILE:.cpp=.o)
TDR_BIN=./tdr_cpp_test
GXX=g++


.PHONY: all clean

all: $(TDR_BIN)

-include $(TDR_CFILE:.cpp=.d)

%.d: %.cpp
	$(GXX) -MM $< -o $@

%.o: %.cpp %.d
	$(GXX) -c  -g $(DEBUG) $<


$(TDR_BIN): $(TDR_OBJ)
	$(GXX) -o $@  $(DEBUG) $^

clean:
	$(RM) *.o  *.d
	$(RM) $(TDR_BIN)
