/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef LOGPARSER_DESC_H
#define LOGPARSER_DESC_H


#ifndef TDR_METALIB_LOGPARSERCONF_VERSION
#define TDR_METALIB_LOGPARSERCONF_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_LOGPARSERCONF_HASH
#define TDR_METALIB_LOGPARSERCONF_HASH 	"6d968dc8566d0afa70cd7ee7dedeec1d" /*hash of metalib*/
#endif
/*
 User Define include[s].   */


/*
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
    #include <stddef.h>
    #include <time.h>
    #include <sys/types.h>

    #if !defined(_WIN32) && !defined(_WIN64)
        #include <stdint.h>
        #include <inttypes.h>

    #else /*if !defined(_WIN32) && !defined(_WIN64)*/

        //The stdint declaras
        typedef  signed char  int8_t;
        typedef  short int16_t;
        typedef  int   int32_t;
        typedef unsigned char  uint8_t;
        typedef unsigned short uint16_t;
        typedef unsigned int   uint32_t;
        #if _MSC_VER >= 1300
            typedef unsigned long long 	uint64_t;
            typedef long long 	int64_t;
        #else /* _MSC_VER */
            typedef unsigned __int64	uint64_t;
            typedef __int64	int64_t;
        #endif /* _MSC_VER */

    #endif /*if !defined(_WIN32) && !defined(_WIN64)*/


    typedef int64_t tdr_longlong;
    typedef uint64_t tdr_ulonglong;
    typedef uint16_t tdr_wchar_t;  /**<Wchar基本数据类型*/
    typedef uint32_t tdr_date_t;	/**<data基本数据类型*/
    typedef uint32_t tdr_time_t;	/**<time基本数据类型*/
    typedef uint64_t tdr_datetime_t; /**<datetime基本数据类型*/
    typedef uint32_t tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct taglogparserconf;
typedef struct taglogparserconf                                    	LOGPARSERCONF;
typedef struct taglogparserconf                                    	*LPLOGPARSERCONF;

struct taglogparser_run_cumulate;
typedef struct taglogparser_run_cumulate                           	LOGPARSER_RUN_CUMULATE;
typedef struct taglogparser_run_cumulate                           	*LPLOGPARSER_RUN_CUMULATE;

struct taglogparser_run_status;
typedef struct taglogparser_run_status                             	LOGPARSER_RUN_STATUS;
typedef struct taglogparser_run_status                             	*LPLOGPARSER_RUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

struct taglogparserconf
{
    char szLogFile[128];
    char szLogFormat[128];
    char szDBMSName[128];
    char szDBMSConnectionInfo[128];
    char szDBMSCurDatabaseName[128];
    char szDBMSUser[128];
    char szDBMSPassword[128];
};

struct taglogparser_run_cumulate
{
    int32_t iRes;
};

struct taglogparser_run_status
{
    int32_t iRes;
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* LOGPARSER_DESC_H */
