import os
Import('buildenv')


src_local = Glob('*.c')
src_local += Glob('*.cpp')

if buildenv.isLinux():
	buildenv.buildExec("recv",src_local,a_tsf4g_static_lib='tsf4g')
else:
	buildenv.buildExec("recv",src_local,CPPDEFINES=['_TSF4G_LARGE_LIB_'],a_tsf4g_static_lib='tsf4g')
