Import('buildenv')
import os

source = Glob('test*.cpp')

if buildenv._isLinux:

    libFlags="-L%s " % os.path.abspath('../../lib_src/gtest/')
    buildenv.buildExec('test',source,a_tsf4g_static_lib="tsf4g",\
            LINKFLAGS=libFlags,LIBS='gtest pthread',\
            CPPPATH=['../../lib_src/gtest/', '../../lib_src/tbus_i/'])
