/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TBUS_ROUTE_H
#define TBUS_ROUTE_H


#ifndef TDR_METALIB_TBUS_VERSION 
#define TDR_METALIB_TBUS_VERSION 	5 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TBUS_HASH 
#define TDR_METALIB_TBUS_HASH 	"7a0f4ed79428114d2ad76a8f0ef33172" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define RELAY_COUNT                              	1024 	/* Only support 1024 relay at one machine */

#endif /* TBUS_ROUTE_H */
