/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

/*       Version Number: 3          */

#ifndef _NET_PROTOCOL_H
#define _NET_PROTOCOL_H

/*   Define c types.   */
#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef unsigned long long tdr_datetime_t; /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif


/*   Define Macros.   */

#define VERSION                                  	100
#define MAX_BODY_LEN                             	32000
#define CMD_LOGIN                                	0
#define CMD_LOGOUT                               	1
#define MAX_NAME_LEN                             	32
#define MAX_PASS_LEN                             	32
#define MAX_ATTR_SIZE                            	128


#ifdef __cplusplus
extern "C" {
#endif

/*   Structs/unions prototype.   */

struct tagPkgHead;
typedef struct tagPkgHead                          	PKGHEAD;
typedef struct tagPkgHead                          	*LPPKGHEAD;

struct tagCmdLogin;
typedef struct tagCmdLogin                         	CMDLOGIN;
typedef struct tagCmdLogin                         	*LPCMDLOGIN;

struct tagCmdLogout;
typedef struct tagCmdLogout                        	CMDLOGOUT;
typedef struct tagCmdLogout                        	*LPCMDLOGOUT;

union tagPkgBody;
typedef union  tagPkgBody                          	PKGBODY;
typedef union  tagPkgBody                          	*LPPKGBODY;

struct tagPkg;
typedef struct tagPkg                              	PKG;
typedef struct tagPkg                              	*LPPKG;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagPkgHead
{
    short nMagic;                         
    short nVersion;                       
    tdr_datetime_t tTime;                          
    short nCmd;                           
    short nBodylen;                       
    unsigned int dwMsgid;                         	/*   message id */
};

struct tagCmdLogin
{
    char szName[MAX_NAME_LEN];           
    char szPass[MAX_PASS_LEN];           
    char szZone[2][MAX_PASS_LEN];        
    char _szPadding1[72];
};

struct tagCmdLogout
{
    int iReason;                        
    char szAttr[MAX_ATTR_SIZE];          
};

union tagPkgBody
{
    CMDLOGIN stLogin;                         	/* CMD_LOGIN,   */
    CMDLOGOUT stLogout;                        	/* CMD_LOGOUT,   */
};

struct tagPkg
{
    PKGHEAD stHead;                         
    PKGBODY stBody;                         
};


#pragma pack()

#ifdef __cplusplus
}
#endif

#endif /* _NET_PROTOCOL_H */
