# The set of source files associated with this SConscript file.
import os

if os.path.isfile('conv.bat'):
	#Cd to the dir and exec conv.bat
	os.system('conv.bat')
	#
Import('buildenv')

src_local = Glob('*.c')
src_local += Glob('*.cpp')
src_local += Glob('../../lib_src/tbus_i/*.c')
#src_local=Glob('tdr.c')
#src_local+=Glob('tgetopt.c')
#src_local+=Glob('tdr_tools.c')

buildenv.VersionHeader(target = ["version.h"],\
                       major=buildenv.getMajor('base'),
                       minor=buildenv.getMinor('base'))

if buildenv._isLinux:
	buildenv.buildTools('trelaymgr',src_local,CPPPATH=Split('../../lib_src'),
    OBJPREFIX="grm",a_tsf4g_static_lib='tsf4g',LIBS='pthread')
else:
	buildenv.buildTools('trelaymgr',src_local, CPPPATH=Split('../../lib_src'),
    CPPDEFINES=Split("_TSF4G_LARGE_LIB_"),OBJPREFIX="grm", a_tsf4g_static_lib='tsf4g')
Return('src_local')
