Import("buildenv")

import os
buildenv.xml2h('mtexample_conf_desc.xml')
buildenv.xml2c('mtexample_conf_desc','mtexample_conf_desc.xml')


src = Glob('*.c')

if buildenv._isLinux:
	buildenv.buildExec('mtexample',src,a_tsf4g_static_lib='tsf4g',LIBS='pthread')
	Install('../../bin/','mtexample')
else:
	buildenv.buildExec('mtexample',src,a_tsf4g_static_lib='tsf4g',CPPDEFINES=['_TSF4G_LARGE_LIB_'])
	Install('../../bin/','mtexample.exe')
