/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef DEPLOY_DEF_H
#define DEPLOY_DEF_H


#ifndef TDR_METALIB_MANAGING_VERSION
#define TDR_METALIB_MANAGING_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_MANAGING_HASH
#define TDR_METALIB_MANAGING_HASH 	"38a1fae5fa173fd90d44e019c9c12921" /*hash of metalib*/
#endif
/*
 User Define Macros.   */

#define MAX_PROC_NUM                             	256
#define MAX_NAME_LEN                             	128
#define MAX_CMD_LEN                              	256
#define BUS_ID_LEN                               	32
#define USER_LEN                                 	32


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if (defined(_WIN32) || defined(_WIN64)) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagMNGPRocAttr;
typedef struct tagMNGPRocAttr                      	MNGPROCATTR;
typedef struct tagMNGPRocAttr                      	*LPMNGPROCATTR;

struct tagHostDeploy;
typedef struct tagHostDeploy                       	HOSTDEPLOY;
typedef struct tagHostDeploy                       	*LPHOSTDEPLOY;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagMNGPRocAttr
{
    char szProcName[MAX_NAME_LEN];
    char szWorkDir[MAX_CMD_LEN];
    char szProcID[BUS_ID_LEN];
    char szUser[USER_LEN];
    char szStartCmd[MAX_CMD_LEN];
    char szStopCmd[MAX_CMD_LEN];
    int iPid;
    int iStatus;
    unsigned int dwStart;
    unsigned int dwStop;
    unsigned int dwActive;
    int iMFlag;                          	/*   mark if be managed! */
};

struct tagHostDeploy
{
    char szAgentId[BUS_ID_LEN];
    int iProcNum;
    MNGPROCATTR astProcessList[MAX_PROC_NUM];
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* DEPLOY_DEF_H */
