import os
Import('buildenv')

buildenv.xml2h('MultiThread_conf_desc.xml')
buildenv.xml2c('MultiThread_conf_desc','MultiThread_conf_desc.xml')

src_local = Glob('*.c')
src_local += Glob('*.cpp')
if buildenv.isLinux():
	buildenv.buildExamples("tlog",'MultiThread',src_local,a_cppdefs='TDR_XML',a_tsf4g_static_lib='tsf4g',LIBS='pthread')
else:
	buildenv.buildExamples("tlog","MultiThread",src_local,CPPDEFINES=['_TSF4G_LARGE_LIB_'],a_tsf4g_static_lib='tsf4g')
#buildenv.addPostAction(buildenv.execKey("TappTlog"),buildenv.postCmd('python '+os.path.abspath('test.py')))

