import os
Import('buildenv')


src_local = Glob('*.c')
src_local += Glob('*.cpp')

if buildenv.isLinux():
	buildenv.buildExamples("tlog","HelloWorld",src_local,a_tsf4g_static_lib='tsf4g')
	buildenv.ttest('HelloWorld.txml','HelloWorld',TESTRETV=0)
else:
	buildenv.buildExamples("tlog","HelloWorld",src_local,CPPDEFINES=['_TSF4G_LARGE_LIB_'],a_tsf4g_static_lib='tsf4g')
	buildenv.ttest('HelloWorld.txml','HelloWorld.exe',TESTRETV=0)

