/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

/*       Version Number: 1          */

#ifndef TLOGCONF_H
#define TLOGCONF_H

/*   Define Macros.   */

#define TLOG_VER                                 	1
#define TLOG_MAGIC                               	55
#define TLOG_ID_CONF                             	1
#define TLOG_ID_BASE                             	2
#define TLOG_ID_HEAD                             	3
#define TLOG_ID_PKG                              	4
#define TLOG_ID_REQ                              	5
#define TLOG_ID_RES                              	6
#define TLOG_URL_LEN                             	128
#define TLOG_METANAME_LEN                        	32
#define TLOG_PATH_LEN                            	128
#define TLOG_PATTERN_LEN                         	128
#define TLOG_MAX_SVR                             	128
#define TLOG_MAX_META                            	128
#define TLOG_MAX_CAT                             	128
#define TLOG_MAX_MAP                             	1024
#define TLOG_MAX_DATA                            	64000


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/

/**<datetime基本数据类型*/
#if defined(_WIN32) || defined(_WIN64)
	#if _MSC_VER < 1300
		typedef unsigned __int64 tdr_datetime_t;
	#else
		typedef unsigned long long tdr_datetime_t;
	#endif /*_MSC_VER*/
#else
	typedef unsigned long long tdr_datetime_t;
#endif

typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/

/*   Structs/unions prototype.   */

struct tagTLOGFilter;
typedef struct tagTLOGFilter                       	TLOGFILTER;
typedef struct tagTLOGFilter                       	*LPTLOGFILTER;

struct tagIDFilter;
typedef struct tagIDFilter                         	IDFILTER;
typedef struct tagIDFilter                         	*LPIDFILTER;

struct tagCatFilter;
typedef struct tagCatFilter                        	CATFILTER;
typedef struct tagCatFilter                        	*LPCATFILTER;

struct tagTLOGPattern;
typedef struct tagTLOGPattern                      	TLOGPATTERN;
typedef struct tagTLOGPattern                      	*LPTLOGPATTERN;

struct tagTLOGSvr;
typedef struct tagTLOGSvr                          	TLOGSVR;
typedef struct tagTLOGSvr                          	*LPTLOGSVR;

struct tagTLOGMeta;
typedef struct tagTLOGMeta                         	TLOGMETA;
typedef struct tagTLOGMeta                         	*LPTLOGMETA;

struct tagTLOGCat;
typedef struct tagTLOGCat                          	TLOGCAT;
typedef struct tagTLOGCat                          	*LPTLOGCAT;

struct tagTLOGMap;
typedef struct tagTLOGMap                          	TLOGMAP;
typedef struct tagTLOGMap                          	*LPTLOGMAP;

struct tagTLOGConf;
typedef struct tagTLOGConf                         	TLOGCONF;
typedef struct tagTLOGConf                         	*LPTLOGCONF;

struct tagTLOGTime;
typedef struct tagTLOGTime                         	TLOGTIME;
typedef struct tagTLOGTime                         	*LPTLOGTIME;

struct tagTLOGBase;
typedef struct tagTLOGBase                         	TLOGBASE;
typedef struct tagTLOGBase                         	*LPTLOGBASE;

struct tagTLOGHead;
typedef struct tagTLOGHead                         	TLOGHEAD;
typedef struct tagTLOGHead                         	*LPTLOGHEAD;

struct tagTLOGPkg;
typedef struct tagTLOGPkg                          	TLOGPKG;
typedef struct tagTLOGPkg                          	*LPTLOGPKG;

struct tagTLOGReq;
typedef struct tagTLOGReq                          	TLOGREQ;
typedef struct tagTLOGReq                          	*LPTLOGREQ;

struct tagTLOGRes;
typedef struct tagTLOGRes                          	TLOGRES;
typedef struct tagTLOGRes                          	*LPTLOGRES;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagTLOGFilter
{
    int iStart;
    int iCount;
    short nMod;
    short nRes;
    short nModStart;
    short nModCount;
};

struct tagIDFilter
{
    int iStart;
    int iCount;
    short nMod;
    short nRes;
    short nModStart;
    short nModCount;
};

struct tagCatFilter
{
    int iStart;
    int iCount;
    short nMod;
    short nRes;
    short nModStart;
    short nModCount;
};

struct tagTLOGPattern
{
    int iStartTime;
    int iLastSec;
    TLOGFILTER stID;
    TLOGFILTER stCat;
    int iInst;
};

struct tagTLOGSvr
{
    int s;
    int iType;
    int iSendBuff;
    int iRecvBuff;
    int iSendMsg;
    int iRecvMsg;
    int iSendByteLow;
    int iSendByteHigh;
    int iRecvByteHigh;
    int iRecvByteLow;
    int iSendSeq;
    int iRecvSeq;
    int iCtrl;
    int iSvrInst;
    IDFILTER stID;
    CATFILTER stCat;
    char szUrl[TLOG_URL_LEN];
};

struct tagTLOGMeta
{
    int iLib;
    int iRes;
    char szPath[TLOG_PATH_LEN];
};

struct tagTLOGCat
{
    IDFILTER stID;
    CATFILTER stCat;
    int iBuffSize;
    int iSizeLimit;
    int iPrecision;
    int iMaxRotate;
    char szPattern[TLOG_PATTERN_LEN];
};

struct tagTLOGMap
{
    int iID;
    int iRes;
    char szName[TLOG_METANAME_LEN];
};

struct tagTLOGConf
{
    int iMaxSvr;
    TLOGSVR astSvrs[TLOG_MAX_SVR];
    int iMaxMeta;
    TLOGMETA astMetas[TLOG_MAX_META];
    int iMaxCat;
    TLOGCAT astCats[TLOG_MAX_CAT];
    int iMaxMap;
    TLOGMAP astMaps[TLOG_MAX_MAP];
};

struct tagTLOGTime
{
    int iSec;
    int iUsec;
};

struct tagTLOGBase
{
    char chVer;
    char chMagic;
    char chCmd;
    char chHeadLen;
    short nInst;
    short nMeta;
    TLOGTIME stTime;
    int iSeq;
    int iID;
    int iCat;
    unsigned short wBodyVer;
    unsigned short wBodyLen;
};

struct tagTLOGHead
{
    char chVer;
    char chMagic;
    char chCmd;
    char chHeadLen;
    short nInst;
    short nMeta;
    TLOGTIME stTime;
    int iSeq;
    int iID;
    int iCat;
    unsigned short wBodyVer;
    unsigned short wBodyLen;
};

struct tagTLOGPkg
{
    TLOGHEAD stHead;
    char szData[TLOG_MAX_DATA];
};

struct tagTLOGReq
{
    int iType;
};

struct tagTLOGRes
{
    int iType;
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TLOGCONF_H */
