# The set of source files associated with this SConscript file.
import os
Import("buildenv")
src_local = Glob('*.c')
src_local += Glob('*.cpp')

if buildenv.isLinux():
	buildenv.buildExamples("tlog",'VecFilter',src_local,a_cppdefs='TDR_XML',a_tsf4g_static_lib='tsf4g')
else:
	buildenv.buildExamples("tlog","VecFilter",src_local,CPPDEFINES=Split('_TSF4G_LARGE_LIB_'),a_tsf4g_static_lib='tsf4g')
#

Return('src_local')

